export const sizeList_DB = [
  { size: "300 ml", price: 6 },
  { size: "400 ml", price: 7 },
  { size: "500 ml", price: 8 },
  { size: "750 ml", price: 9 },
  { size: "1 litro", price: 10 },
];

export const IncrementList_DB = [
  { name: "Aveia", price: 2 },
  { name: "Beijinho", price: 2 },
  { name: "Bis", price: 3 },
  { name: "Chocolate Branco", price: 2 },
  { name: "Chocolate", price: 1 },
  { name: "Coco Ralado", price: 1 },
  { name: "Diamante Negro", price: 2 },
  { name: "Leite Ninho", price: 2 },
  { name: "Gotas de chocolate", price: 2 },
  { name: "Granola", price: 2 },
  { name: "Granulado", price: 1 },
  { name: "Iogurte", price: 1 },
  { name: "Leite Condensado", price: 1 },
  { name: "Leite em pó", price: 2 },
  { name: "Negresco", price: 2 },
  { name: "Nutella", price: 4 },
  { name: "Ouro Branco", price: 2 },
  { name: "Paçoca", price: 1 },
  { name: "Prestígio", price: 2 },
  { name: "Sensação", price: 2 },
  { name: "Sonha do Valsa", price: 3 },
  { name: "Space Ball", price: 2 },
  { name: "Sucrilhos", price: 2 },
  { name: "Ovo Maltini", price: 2 },
];
